version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - dotnet build Bank/Bank.csproj
      - dotnet test BankTest --logger trx --results-directory ./TestResults
      - pwd
      - ls
      - cd bankinfra
      - ls
      - cdk synth
      - cat cdk.out/BankinfraStack.template.json
      - cd ..
  post_build:
    commands:
      - dotnet publish -r linux-x64 Bank/Bank.csproj
      - mkdir binaries
      - cp -r Bank/bin/Debug/net6.0/linux-x64/publish/* binaries
reports:
  dotnetcicdtest:
    files:
      - '**/*'
    base-directory: './TestResults'
    file-format: VisualStudioTrx
artifacts:
  files:
    - Bank/bin/Debug/net6.0/linux-x64/publish/**/*
  discard-paths: yes
  secondary-artifacts:
    cloudformation:
      files:
        - bankinfra/cdk.out/BankinfraStack.template.json
      discard-paths: yes
    application:
      files:
        - binaries/**/*
        - scripts/**/*
      discard-paths: no
  
